Repository 1313BAN/team01-Bango-BE, pull requests merged in 2025-05, with the labels that each got.

#26 [FEAT] Spring AI 기반 매물 주변 정보 요약 프롬프트 구현
  build.gradle
  src/main/java/com/ssafy/bango/domain/ai/controller/AiController.java
  src/main/java/com/ssafy/bango/domain/ai/service/AiChatService.java
  src/main/java/com/ssafy/bango/global/auth/security/AuthWhiteList.java
  src/main/java/com/ssafy/bango/global/config/AiConfig.java
  src/main/resources/application.yaml
Labels: ✨ feat ✨

#28 [Feat] API 호출 오류 해결
  src/main/java/com/ssafy/bango/domain/rentalhouse/service/KakaoGeocodingService.java
  src/main/resources/application.yaml
Labels: 🚨 fix 🚨

#30 Feature/member api integration #29
  src/main/java/com/ssafy/bango/domain/member/controller/MemberController.java
  src/main/java/com/ssafy/bango/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/ssafy/bango/domain/member/dto/response/TokenResponse.java
  src/main/java/com/ssafy/bango/domain/member/service/MemberService.java
  src/main/java/com/ssafy/bango/global/config/SecurityConfig.java
Labels: ✨ feat ✨, 🚨 fix 🚨

#31 [Refactor] 스웨거 설정 및 설명 추가
  src/main/java/com/ssafy/bango/domain/ai/controller/AiApi.java
  src/main/java/com/ssafy/bango/domain/ai/controller/AiController.java
  src/main/java/com/ssafy/bango/domain/dongcode/controller/DongCodeApi.java
  src/main/java/com/ssafy/bango/domain/member/controller/MemberApi.java
  src/main/java/com/ssafy/bango/domain/noticelike/controller/NoticeLikeApi.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/controller/RentalHouseApi.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/controller/RentalHouseController.java
  src/main/java/com/ssafy/bango/domain/rentalnotice/controller/RentalNoticeApi.java
  src/main/java/com/ssafy/bango/global/auth/security/AuthWhiteList.java
  src/main/java/com/ssafy/bango/global/config/SwaggerConfig.java
  src/main/java/com/ssafy/bango/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yaml
Labels: 🚨 fix 🚨, ♻️ refactor ♻️

#34 [Refactor] Swagger 설명 누락 및 개발용 컨트롤러 분리
  src/main/java/com/ssafy/bango/domain/rentalhouse/service/KakaoFacilityService.java
  src/main/java/com/ssafy/bango/global/common/health/BatchController.java
  src/main/java/com/ssafy/bango/global/common/health/GeocodingController.java
  src/main/java/com/ssafy/bango/global/common/health/HealthController.java
  src/main/java/com/ssafy/bango/global/config/SwaggerConfig.java
Labels: ♻️ refactor ♻️

#35 [Feat] 구/동별 임대주택 개수 및 위경도 정보 조회
  src/main/java/com/ssafy/bango/domain/dongcode/entity/DongCode.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/controller/RentalHouseApi.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/controller/RentalHouseController.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/controller/RentalHouseSummaryApi.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/controller/RentalHouseSummaryController.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/dto/request/LatLongBoundsRequest.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/dto/request/RentalHouseSummaryRequest.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/dto/response/DongSummaryResponse.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/dto/response/GeoPointResponse.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/dto/response/GugunSummaryResponse.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/entity/RentalHouse.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/entity/RentalHouseSummary.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/repository/RentalHouseRepository.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/repository/RentalHouseStyleRepository.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/repository/RentalHouseSummaryRepository.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/service/KakaoGeocodingService.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/service/RentalHouseService.java
  src/main/java/com/ssafy/bango/domain/rentalhouse/service/RentalHouseSummaryService.java
  src/main/java/com/ssafy/bango/global/batch/chunk/facility/v1/FacilityApiItemProcessor.java
  src/main/java/com/ssafy/bango/global/batch/job/RentalHouseBatchConfiguration.java
  src/main/java/com/ssafy/bango/global/batch/job/RentalHouseBatchJobConfig.java
  src/main/java/com/ssafy/bango/global/batch/job/RentalHouseChunkConfig.java
  src/main/java/com/ssafy/bango/global/batch/job/v1/FacilityBatchConfiguration.java
  src/main/java/com/ssafy/bango/global/batch/tasklet/RentalHouseDeleteDataTasklet.java
  src/main/java/com/ssafy/bango/global/batch/tasklet/RentalHouseSummaryGenerateTasklet.java
  src/main/java/com/ssafy/bango/global/batch/tasklet/v1/FacilityDeleteDataTasklet.java
  src/main/java/com/ssafy/bango/global/exception/enums/SuccessType.java
  src/main/java/com/ssafy/bango/global/scheduler/OpenApiScheduler.java
  src/main/java/com/ssafy/bango/global/validation/LatLongBoundsValidator.java
  src/main/java/com/ssafy/bango/global/validation/ValidLatLongBounds.java
Labels: ✨ feat ✨, ♻️ refactor ♻️, ⚡ perf ⚡

#38 [Style] 스웨거 설명 수정
  src/main/java/com/ssafy/bango/domain/noticelike/controller/NoticeLikeApi.java
  src/main/java/com/ssafy/bango/domain/rentalnotice/controller/RentalNoticeApi.java
  src/main/java/com/ssafy/bango/global/auth/security/AuthWhiteList.java
Labels: 🎨 style 🎨

#41 [Feat] monitoring #32
  Dockerfile-local
  build.gradle
  docker-compose.yml
  gradlew
  src/main/java/com/ssafy/bango/global/auth/security/AuthWhiteList.java
  src/main/java/com/ssafy/bango/global/batch/chunk/rentalhouse/RentalHouseApiItemReader.java
  src/main/java/com/ssafy/bango/global/batch/chunk/rentalhouse/RentalHouseApiItemWriter.java
  src/main/java/com/ssafy/bango/global/config/RedisConfig.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/main/resources/dongcode_dump.sql
Labels: ✨ feat ✨

#43 [FEAT] 공고 필터링 검색 API 구현
  src/main/java/com/ssafy/bango/domain/rentalnotice/controller/RentalNoticeApi.java
  src/main/java/com/ssafy/bango/domain/rentalnotice/controller/RentalNoticeController.java
  src/main/java/com/ssafy/bango/domain/rentalnotice/repository/RentalNoticeRepository.java
  src/main/java/com/ssafy/bango/domain/rentalnotice/service/RentalNoticeService.java
  src/main/java/com/ssafy/bango/global/util/RentalNoticeSpecifications.java
Labels: ✨ feat ✨, ♻️ refactor ♻️

#44 [CHORE] NoticeLike 공통 url 변경
  src/main/java/com/ssafy/bango/domain/noticelike/controller/NoticeLikeController.java
Labels: 🔧 chore 🔧
